steps:
- name: 'python:3.7'
  entrypoint: bash
  # Run pip install and pytest in the same build step
  # (pip packages won't be preserved in future steps!)
  args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
  dir: 'function/dir/from/repo/root'